<a href="https://colab.research.google.com/github/kushalhole/Data_science_lab_SE_20/blob/main/ds3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Create a 3x3 square matrix
# Modified the last element to make the matrix invertible
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 10]]) # Changed from 9 to 10

print("Modified 3x3 Matrix:")
print(matrix_3x3)

# Compute the determinant of the modified matrix
determinant = np.linalg.det(matrix_3x3)

print("\nDeterminant of the modified matrix:")
print(determinant)

Modified 3x3 Matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Determinant of the modified matrix:
-2.9999999999999996


In [4]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 3],
              [4, 5]])

# Define the constant vector B
B = np.array([10, 20])

# Solve the system of linear equations
# The function np.linalg.solve(A, B) computes the solution x to the linear system Ax = B.
x_y = np.linalg.solve(A, B)

print("Coefficient matrix A:")
print(A)
print("\nConstant vector B:")
print(B)
print("\nSolution (x, y):")
print(x_y)

Coefficient matrix A:
[[2 3]
 [4 5]]

Constant vector B:
[10 20]

Solution (x, y):
[5. 0.]


In [3]:
# Compute the inverse of the modified matrix
inverse_matrix = np.linalg.inv(matrix_3x3)

print("\nInverse of the modified matrix:")
print(inverse_matrix)


Inverse of the modified matrix:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
